name: push tags branches

on:
  push:
    tags:
      - "*"

jobs:
  apply:
    name: Deploy auxo gateway
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install redis
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.TKE_CONFIG_DATA }}
        with:
          args: helm upgrade --install --namespace redis -f values-production.yaml redis ./redis
